; minikb — firmware Arduino-Pico via PlatformIO (RP2040).
; Tastiera USB HID + slave I2C CardKB + LED WS2812 di stato su GP28.
[env:minikb]
; core earlephilhower (arduino-pico) tramite la platform di maxgerhardt
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
build_flags =
    -D USE_TINYUSB
lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.0
